### ISSUE TITLE
FactoryGirl -> FactoryBot

### ISSUE THREAD

**Issue by ywwg** [FireflyArtsCollective/ffagc#114]
FactoryGirl has been deprecated in favor of FactoryBot. The migration is not trivial, though, so it requires more work than just search-and-replace

**Comment by May-Lee** [comment]
What kind of issues do you foresee in the migration? Or what should I look out for?

**Comment by ywwg** [comment]
btw this message appears when I run rake to check my tests.

It looks like the way the factory objects are constructed has changed between factorygirl and factorybot.  I tried just search-and-replacing all instances of "girl" to "bot" and it threw an error.

**Comment by ywwg** [comment]
instructions: "DEPRECATION WARNING: The factory_girl gem is deprecated. Please upgrade to factory_bot. See https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md for further instructions."

**Comment by ywwg** [comment]
This was also quite tricky! The syntax changed in a way that was hard to figure out
