### ISSUE TITLE
sass deprecated sigggghhhhh

### ISSUE THREAD

**Issue by ywwg** [FireflyArtsCollective/ffagc#120]
ill be unmaintained as of 26 March 2019.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  http://sass.logdown.com/posts/7081811

**Comment by ywwg** [comment]
I thought I fixed this but this message still appeared

**Comment by May-Lee** [comment]
Can you tell me when this message appears?

**Comment by ywwg** [comment]
I think it appears when I run "bundle update"? But it's not happening now so maybe it's not broken after all???  Let's just keep an eye out for this message and if it doesn't pop up again in a few months I'll close the issue

**Comment by May-Lee** [comment]
Sounds good; I couldn't find the issue. None of the scss/css has conflicting syntax and ruby sass is out of the gemfile.

**Comment by ywwg** [comment]
seems to be fixed
