### ISSUE TITLE
pdf generation not working (503 error)

### ISSUE THREAD

**Issue by ywwg** [FireflyArtsCollective/ffagc#51]
I'm getting a 503 error, not sure why

**Comment by ywwg** [comment]
ok the 503 means not authorized, but then rails also says we don't have a template for a pdf version of the 503 error page (lol)

**Comment by ywwg** [comment]
the link for generation is showing up as "http://localhost:3000/grant_submissions/1/generate_contract.pdf"
which is not right, it should be a post request to something like http://localhost:3000/grant_submissions/generate_contact/"... maybe?  Not sure what's going on here.

**Comment by ywwg** [comment]
I don't know enough about how this changed to fix this and contract generation is a Major Issue so @Katee can you take a look at this?

**Comment by NatMorcos** [comment]
I'm not able to assign myself to this in the sidebar - but I can take a look at this one :)

**Comment by ywwg** [comment]
looks like we can only officially assign people who are part of the Organization.  thanks for taking a look!

**Comment by Katee** [comment]
I jumped in and opened a PR for this: https://github.com/FireflyArtsCollective/ffagc/pull/53
