### ISSUE TITLE
Cut-and-pastable list of verified voters

### ISSUE THREAD

**Issue by ywwg** [FireflyArtsCollective/ffagc#90]
One thing that comes up often is needing to send a quick email to all the verified voters.  In fact a little birdie tells me we're going to need to do just that real soon.  A simple comma-separated list that an admin can cut and paste into an email compose box works best here.

(We don't want the portal to become and email composer)

**Comment by Katee** [comment]
I didn't realize you where doing this. I did scoping + CSV download button: https://github.com/FireflyArtsCollective/ffagc/pull/92

**Comment by ywwg** [comment]
oh sorry!

**Comment by ywwg** [comment]
Happy to roll back and use your nicer solution

**Comment by ywwg** [comment]
I'll be better about assigning myself in the future

**Comment by Katee** [comment]
No worries! I think both solutions can work together. Your list is definitely easier for just sending an email to everyone.

**Comment by ywwg** [comment]
I also keep promising to make better bug descriptions and I swear I will start doing that too :P

**Comment by ywwg** [comment]
I'll leave my changes committed, if you want to incorporate the filters as well that would be A+

**Comment by ywwg** [comment]
refixed by #92
