### ISSUE TITLE
Grant expiration times are wrong

### ISSUE THREAD

**Issue by ywwg** [FireflyArtsCollective/ffagc#94]
It us 6:39 on feb 18, and the grants page says:

Submission ends: Monday, 2018/02/19  21 minutes from now 

A) that date should be inclusive, not exclusive (submissions accepted until 2am on tuesday, in fact)
B) smells like GMT.  We should be using the configured time zone

**Comment by ywwg** [comment]
currently setting to low priority because I suspect this is only a problem with the display, not with the actual code, which uses the 2am fudge and timezone

**Comment by ywwg** [comment]
anniversary and temple closed at 0000UTC on the 19th, which is wrong.  Raising to high priority

**Comment by ywwg** [comment]
Ah, I'm now remembering that we did have to set deadlines to the next day to make the math work...  I think the issue was that deadlines were stored as UTC from the original grant modification page (as opposed to dates without times).

**Comment by Katee** [comment]
Currently everything is in UTC. You can set the times to the local timezone with something like this:

```ruby
grants = Grant.all
date_attributes = %i[submit_start submit_end vote_start vote_end meeting_one meeting_two]
grants.each do |grant|
  date_attributes.each do |date_attr|
    date = grant.send(date_attr)
    local_date = ActiveSupport::TimeZone.new('America/New_York').local_to_utc(date)
    grant.send("#{date_attr}=", local_date)
  end
  grant.save!
end
```

This code isn't idempotent, it will continue moving dates up by a few hours if run repeatedly.

**Comment by ywwg** [comment]
currently the dates in the db are "datetime," should they have been just "date"s?

**Comment by ywwg** [comment]
would that code snippet be adaptable to work in grants_controller so we save the correct time in the db?

**Comment by ywwg** [comment]
todo: write tests for this :(

**Comment by ywwg** [comment]
this is fixed though!
